# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTcUmf7h4964DbVTRVCU6aIk4f08_y5K
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# =========================
# 1. LOAD DATA
# =========================
zhvi_df = pd.read_csv("County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv")
zori_df = pd.read_csv("County_zori_uc_sfrcondomfr_sm_month.csv")
census = pd.read_csv("ACSDT5Y2024.B19013-Data.csv")

# =========================
# 2. BASELINE MODEL
# Predict 2025 rent using 2024 home value and 2024 rent
# =========================
model_df = pd.DataFrame({
    "ZHVI_2024": pd.to_numeric(zhvi_df["2024-12-31"], errors="coerce"),
    "ZORI_2024": pd.to_numeric(zori_df["2024-12-31"], errors="coerce"),
    "ZORI_2025": pd.to_numeric(zori_df["2025-12-31"], errors="coerce")
}).dropna()

X = model_df[["ZHVI_2024", "ZORI_2024"]]
y = model_df["ZORI_2025"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

# Random Forest
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

print("=== BASELINE MODELS ===")
print("Linear RMSE:", np.sqrt(mean_squared_error(y_test, lr_pred)))
print("Linear R2:", r2_score(y_test, lr_pred))
print()
print("Random Forest RMSE:", np.sqrt(mean_squared_error(y_test, rf_pred)))
print("Random Forest R2:", r2_score(y_test, rf_pred))

# =========================
# 3. CLEAN CENSUS DATA
# =========================
census = census.rename(columns={"B19013_001E": "Median_Income"})
census = census[census["NAME"].notna()].copy()
census = census[census["NAME"] != "Geographic Area Name"].copy()
census = census[census["NAME"] != "United States"].copy()

census[["RegionName", "StateName"]] = census["NAME"].str.split(",", n=1, expand=True)
census["RegionName"] = census["RegionName"].str.strip()
census["StateName"] = census["StateName"].str.strip()

state_to_abbr = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR",
    "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE",
    "District of Columbia": "DC", "Florida": "FL", "Georgia": "GA", "Hawaii": "HI",
    "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA",
    "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME",
    "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN",
    "Mississippi": "MS", "Missouri": "MO", "Montana": "MT", "Nebraska": "NE",
    "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM",
    "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH",
    "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI",
    "South Carolina": "SC", "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX",
    "Utah": "UT", "Vermont": "VT", "Virginia": "VA", "Washington": "WA",
    "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY"
}

census["StateName"] = census["StateName"].map(state_to_abbr)
census["Median_Income"] = pd.to_numeric(census["Median_Income"], errors="coerce")
census = census[["RegionName", "StateName", "Median_Income"]].copy()

# =========================
# 4. MODEL WITH CENSUS
# =========================
full_df = zhvi_df[["RegionName", "StateName"]].copy()
full_df["ZHVI_2024"] = pd.to_numeric(zhvi_df["2024-12-31"], errors="coerce")
full_df["ZORI_2024"] = pd.to_numeric(zori_df["2024-12-31"], errors="coerce")
full_df["ZORI_2025"] = pd.to_numeric(zori_df["2025-12-31"], errors="coerce")

full_df = full_df.merge(census, on=["RegionName", "StateName"], how="left")
full_df = full_df.dropna()

X_census = full_df[["ZHVI_2024", "ZORI_2024", "Median_Income"]]
y_census = full_df["ZORI_2025"]

Xc_train, Xc_test, yc_train, yc_test = train_test_split(
    X_census, y_census, test_size=0.2, random_state=42
)

# Linear + Census
lr_c = LinearRegression()
lr_c.fit(Xc_train, yc_train)
lr_c_pred = lr_c.predict(Xc_test)

# Random Forest + Census
rf_c = RandomForestRegressor(random_state=42)
rf_c.fit(Xc_train, yc_train)
rf_c_pred = rf_c.predict(Xc_test)

print("\n=== MODELS WITH CENSUS ===")
print("Linear + Census RMSE:", np.sqrt(mean_squared_error(yc_test, lr_c_pred)))
print("Linear + Census R2:", r2_score(yc_test, lr_c_pred))
print()
print("Random Forest + Census RMSE:", np.sqrt(mean_squared_error(yc_test, rf_c_pred)))
print("Random Forest + Census R2:", r2_score(yc_test, rf_c_pred))

if r2_score(yc_test, lr_c_pred) > r2_score(yc_test, rf_c_pred):
    print("\nBest Model: Linear Regression")
else:
    print("\nBest Model: Random Forest")

# =========================
# 5. LANDLORD VS FLIPPER ANALYSIS
# =========================
df = zhvi_df[["RegionName", "StateName"]].copy()
df["ZHVI"] = pd.to_numeric(zhvi_df["2025-12-31"], errors="coerce")
df["ZORI"] = pd.to_numeric(zori_df["2025-12-31"], errors="coerce")
df = df.dropna()

df["Annual_Rent"] = df["ZORI"] * 12
df["Rent_Yield"] = (df["Annual_Rent"] / df["ZHVI"]) * 100

zhvi_2024 = pd.to_numeric(zhvi_df["2024-12-31"], errors="coerce")
zhvi_2025 = pd.to_numeric(zhvi_df["2025-12-31"], errors="coerce")

df["Appreciation"] = ((zhvi_2025 - zhvi_2024) / zhvi_2024) * 100
df["Landlord_Advantage"] = df["Rent_Yield"] - df["Appreciation"]

top_landlord = df.sort_values("Landlord_Advantage", ascending=False).head(10)

print("\n=== TOP 10 LANDLORD COUNTIES ===")
print(top_landlord[["RegionName", "StateName", "Rent_Yield", "Appreciation", "Landlord_Advantage"]])

# =========================
# 6. VISUALIZATION
# =========================
plt.figure(figsize=(10, 6))
plt.scatter(df["Rent_Yield"], df["Appreciation"], alpha=0.4)
plt.xlabel("Rent Yield (%)")
plt.ylabel("Appreciation (%)")
plt.title("Landlord vs Flipper")
plt.grid(True, alpha=0.3)
plt.show()